### PR TITLE
Update from original

### PR DESCRIPTION
**Pull request by likso**

### CODE REVIEW

**Comment by braverock** [comment]
You've marked this as closed, and haven't given much motivation or commentary for your proposed change.  You've also left commented code in the proposed patch.  Please provide more information.

**Comment by likso** [comment]
Sorry. I was suppose to rebase your latest master to my two fixes, but I got the other way round. so I closed this requests. However, I am very happy to provide more details to help with the potential bugs.

1) The buy limit order should be filled at the open price instead (fill at limit price previously) in gap down open situation.

2) For OHLC data, the trailing stop price moving logic should based on highest high/ lowest low instead of the closing price.

**Comment by braverock** [comment]
We only really use OHLC data for demo scripts, so I'm certainly open to changes in that code path.

for 1., I'm not sure I agree.  The vast majority of liquid markets globally are open 24 hrs per day, or close to that.  So 'gap open' is kind of a throwback to an era that doesn't really exist anymore.  Either that, or your broker is taking advantage of you by not filling your order in the overnight market.

for 2., this is probably reasonable.

**Comment by joshuaulrich** [comment]
Can you please clarify your 2nd item?

My current understanding of stoplimit behavior on OHLC data is that a sell stoplimit order price will be based on the high price, but the order evaluation is based on the close price.  That means the stoplimit will only be moved if the close is >= order price + threshold.  And when it is moved, the new order price will be high - threshold.

I mentioned this to Derek Wong in an [R-SIG-Finance thread](https://stat.ethz.ch/pipermail/r-sig-finance/2016q1/013789.html) about a year ago.  Here is his response:

> The confusing part for that was using the OHLC data and mixing the close price as a "filter" rather than just highest high lowest low. Also for the fills as well, as a close below the stop limit order is not really realistic. As you can be filled by the low of the day and still have the close above (high of the day and close below for a short), in reality you would have obtained a fill in the market. This is assuming that the stoptrailing order is in the market as it executes at the limit price. But in the back test you would still be maintaining a position as the order would not be filled. This leads to some disparity in the results as only winners would not be filled and continue higher but any losers would be cut off properly. When in reality both would have been closed. I believe this backtesting behavior biases the returns upwards when using the stoptrailing order.

**Comment by likso** [comment]
Hi Josh,

My understanding is fully aligned with Derek. Should use highest high to move the stoplimit price in the stoptrailing order.

**Pull request closed without merging**
